name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest
    env:    # The variables to set for your project and organization
      codescan_org: 123
      codescan_project_key: Dheeraj0305-actionsscanner
      codescan_token: ${{ secrets.actions1 }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1.1.0

    - name: Run Codescan On Push
      if: github.event_name == 'push'
      run: |
        sfdx codescan:run --token=$codescan_token --projectkey=$codescan_project_key --organization=$codescan_org -Dsonar.branch.name=$branch_name
    
    - name: Run Codescan On PR
      if: github.event_name == 'pull_request'
      env:  
        branch_name: ${{ github.ref }}
        target: ${{github.base_ref}}
        branch_type: SHORT 
      run: |
        sfdx codescan:run --token=$codescan_token --projectkey=$codescan_project_key --organization=$codescan_org -Dsonar.branch.name=$branch_name -Dsonar.branch.target=$target -Dsonar.branch.type=$branch_type
    - name: CodeScan Scanner
  # You may pin to the exact commit or the version.
  # uses: codescan-io/codescan-scanner-action@5b2e8c5683ef6a5adc8fa3b7950bb07debccce12
      uses: codescan-io/codescan-scanner-action@1.2
    # CodeScanCloud endpoint for your project
        codeScanUrl: # optional, default is https://app.codescan.io/
    # This task will poll CodeScanCloud until the analysis is completed, or until the timeout is reached
        pollingTimeoutSec: # optional, default is 900
    # The flag to indicate that SARIF file should be generated
        generateSarifFile: # optional, default is true
    # Additional arguments to the sonarcloud scanner
        args: # optional
