name: CI
on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2

      - name: CodeScan Scanner
        uses: codescan-io/codescan-scanner-action@1.2
        with:
          organization: 123
          projectKey: Dheeraj0305-actionsscanner
          login: ${{ secrets.actions1 }}
          codeScanUrl: https://app.codescan.io/
