name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SFDX
        env:
          SFDX_AUTOUPDATE_DISABLE: false
          SFDX_USE_GENERIC_UNIX_KEYCHAIN: true
          SFDX_DOMAIN_RETRY: 300
          SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_CREATE: true
          SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_VERSION_CREATE: true
        run: |
          mkdir /tmp/sfdx
          wget -q https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz -O /tmp/sfdx/sfdx-linux-amd64.tar.xz
          tar xJf /tmp/sfdx/sfdx-linux-amd64.tar.xz -C /tmp/sfdx/ --strip-components 1
          /tmp/sfdx/install

          echo y|sfdx plugins:install sfdx-codescan-plugin
    
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: CodeScan Scanner
        uses: codescan-io/codescan-scanner-action@1.2
        with:
          organization: 123
          projectKey: Dheeraj0305-actionsscanner
          login: ${{ secrets.actions1 }}
          codeScanUrl: https://app.codescan.io/
          pollingTimeoutSec: 900
      - name: Run Codescan On Push
        if: github.event_name == 'push'
        env: 
          branch_name: ${{ github.ref }}
          target: ${{github.base_ref}}
          branch_type: SHORT 
          generateSarifFile: true
          key: ${{ secrets.actions1 }} 
          run: |
            sfdx codescan:run --token=$codescan_token --projectkey=$codescan_project_key --organization=$codescan_org -Dsonar.branch.name=$branch_name
