name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: CodeScan Scanner
        uses: codescan-io/codescan-scanner-action@1.2
        with:
          organization: 123
          projectKey: Dheeraj0305-actionsscanner
          login: ${{ secrets.actions1 }}
          codeScanUrl: https://app.codescan.io/
          pollingTimeoutSec: 900
      - name: Run Codescan On Push
        if: github.event_name == 'push'
        env: 
          branch_name: ${{ github.ref }}
          target: ${{github.base_ref}}
          branch_type: SHORT 
          generateSarifFile: true
          key: ${{ secrets.actions1 }} 
          run: |
            sfdx codescan:run --token=$codescan_token --projectkey=$codescan_project_key --organization=$codescan_org -Dsonar.branch.name=$branch_name
